# This file is typically maintained with the following procedure:
#
#  1. edit this file 
#  2. git commit and git push to repo
#  3. in the "app-loki" pod, exec a shell in the "app-loki-tools" container
#  4. run "/tools/etc/update.sh"

lokiURL: http://app-loki.drowningfrog.homenet.org:3100
preAction: /tools/loki-actions/actions.sh pre
postAction: /tools/loki-actions/actions.sh post
lastRun: /tools/etc/loki-actions.lastrun
period: 600
jobs:

  - name: vtund sessions
    query: "{job=\"messages\"} |= \"vtund\" |= \"Session\""
    action: "cat >>/tmp/events"

  - name: firehose/firebox logins
    query: "{job=\"syslog_messages\"} |~ \"fire(box|hose)\" |= \"Accepted\""
    action: "cat >>/tmp/events"

  - name: IO errors
    query: "{job=\"syslog_messages\"} |~ \"I/O error\" != \"Dad-iMac\""
    action: "cat >>/tmp/events"

  - name: kernel stacktrace
    query: "{job=\"syslog_messages\"} |~ \"kernel: Call Trace\""
    action: "cat >>/tmp/events"

  - name: nybox/sfbox logins
    query: "{job=\"syslog_messages\"} |~ \"(nybox|sfbox)\" |= \"Accepted\" != \"SHA256:e752M1pjHLvVc\""
    action: "cat >>/tmp/events"

  - name: zpool event
    query: "{job=\"syslog_messages\"} |~ \"vdev state changed\""
    action: "cat >>/tmp/events"

  - name: new SSL certificate
    query: "{job=\"syslog_messages\"} |~ \"New certificate\""
    action: "cat >>/tmp/events"

  - name: minecraft connection attempts
    query: "{job=\"syslog_messages\"} |= \"firebox kernel:\" |= \"minecraft\" |= \"SYN\""
    action: "cat >>/tmp/events"

