# This is my github actions workflow.

name: DoBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - env:
          NUKE_LAUNCH_CODE: ${{ secrets.HELLOSECRET }}
      - run: |
          echo "Using secret code ($NUKE_LAUNCH_CODE)."
          go get gopkg.in/yaml.v2
          go build loki-actions.go
          ./loki-actions || echo "=== Success ==="

